### ISSUE TITLE
ves function fails with colnames error if h=1

### ISSUE THREAD

**Issue by BerriJ** [config-i1/legion#20]
Hi config-i1,

thanks for your package! I like it. However, I ran into a little bug today. We can reproduce that easily using the Example code:

```
library(legion)
Y <- ts(cbind(
    1000 + 0.5 * c(1:100) + rnorm(100, 0, 10),
    cbind(1000 + 1.5 * c(1:100) + rnorm(100, 0, 10))
),
frequency = 12
)
ves(Y, h = 2, holdout = TRUE, silent = FALSE)
ves(Y, h = 1, holdout = TRUE, silent = FALSE)
```

The second call to `ves` (the one with `h=1`) throws errors with the following message:

```
Error in `colnames<-`(`*tmp*`, value = dataNames) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

I guess that there is an object that becomes a vector if `h=1` and therefore looses its colnames attribute.

Maybe you can look into that. Or provide some guidance on how to fix it myself. I'd be more than happy to open a PR. 

Thanks in advance
BerriJ

**Comment by config-i1** [comment]
Hi!

Thanks for reporting this. It should be fixed in v0.1.2.41005 (8ef66a08255d61557e0ae3b8f561805cebbd00a0) Please, install the package from github to test.
